package keyword

var ReservedForTableAlias = map[KeyWord]struct{}{
	// Reserved as both a table and a column alias:
	WITH:      {},
	EXPLAIN:   {},
	ANALYZE:   {},
	SELECT:    {},
	WHERE:     {},
	GROUP:     {},
	SORT:      {},
	HAVING:    {},
	ORDER:     {},
	PIVOT:     {},
	UNPIVOT:   {},
	TOP:       {},
	LATERAL:   {},
	VIEW:      {},
	LIMIT:     {},
	OFFSET:    {},
	FETCH:     {},
	UNION:     {},
	EXCEPT:    {},
	INTERSECT: {},
	// Reserved only as a table alias in the `FROM`/`JOIN` clauses:
	ON:         {},
	JOIN:       {},
	INNER:      {},
	CROSS:      {},
	FULL:       {},
	LEFT:       {},
	RIGHT:      {},
	NATURAL:    {},
	USING:      {},
	CLUSTER:    {},
	DISTRIBUTE: {},
	// for MSSQL-specific OUTER APPLY (seems reserved in most dialects)
	OUTER:   {},
	SET:     {},
	QUALIFY: {},
	WINDOW:  {},
	END:     {},
	FOR:     {},
	// for MYSQL PARTITION SELECTION
	PARTITION: {},
}

var ReservedForColumnAlias = map[KeyWord]struct{}{
	// Reserved as both a table and a column alias:
	WITH:       {},
	EXPLAIN:    {},
	ANALYZE:    {},
	SELECT:     {},
	WHERE:      {},
	GROUP:      {},
	SORT:       {},
	HAVING:     {},
	ORDER:      {},
	TOP:        {},
	LATERAL:    {},
	VIEW:       {},
	LIMIT:      {},
	OFFSET:     {},
	FETCH:      {},
	UNION:      {},
	EXCEPT:     {},
	INTERSECT:  {},
	CLUSTER:    {},
	DISTRIBUTE: {},
	RETURNING:  {},
	// Reserved only as a column alias in the `SELECT` clause
	FROM: {},
	INTO: {},
	END:  {},
}
